import { jsPDF } from "jspdf";

export type AnyOutput = Record<string, any>;

export function previewText(generator_type: string, output: AnyOutput): string {
  if (generator_type === "instagram_caption") {
    return (output?.captions ?? [])
      .map((c: any, i: number) => `Caption ${i + 1}\n${c.text}\n${(c.hashtags ?? []).map((h: string) => `#${h.replace(/^#/, "")}`).join(" ")}`)
      .join("\n\n");
  }
  if (generator_type === "whatsapp_campaign") {
    return (output?.messages ?? []).map((m: any, i: number) => `Message ${i + 1} — ${m.label ?? ""}\n${m.body}`).join("\n\n");
  }
  if (generator_type === "flyer_copy") {
    return [
      output?.headline,
      output?.subheadline,
      ...(output?.bullets ?? []).map((b: string) => `• ${b}`),
      output?.cta,
    ].filter(Boolean).join("\n");
  }
  if (generator_type === "content_calendar") {
    return (output?.plan ?? [])
      .map((d: any) => `Day ${d.day} — ${d.theme}\n${d.hook ?? ""}\n${d.caption ?? ""}\nCTA: ${d.cta ?? ""}`)
      .join("\n\n");
  }
  if (generator_type === "image") {
    return output?.prompt ?? "Generated image";
  }
  return JSON.stringify(output, null, 2);
}

export function downloadBlob(content: string, filename: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function exportPDF(opts: { title: string; body: string; brand?: string }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const margin = 48;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const usable = pageWidth - margin * 2;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text(opts.title, margin, margin + 8);

  if (opts.brand) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(opts.brand, margin, margin + 26);
    doc.setTextColor(0);
  }

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(opts.body, usable);
  let y = margin + 56;
  const lineHeight = 16;
  for (const line of lines) {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineHeight;
  }

  doc.setFontSize(9);
  doc.setTextColor(140);
  doc.text(`Generated by ContentNaija AI • ${new Date().toLocaleDateString()}`, margin, pageHeight - 24);

  doc.save(`${opts.title.replace(/[^a-z0-9-_]+/gi, "_").toLowerCase()}.pdf`);
}

function icsEscape(s: string) {
  return s.replace(/\\/g, "\\\\").replace(/\n/g, "\\n").replace(/,/g, "\\,").replace(/;/g, "\\;");
}

function fmtDate(d: Date) {
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}00Z`;
}

export function exportCalendarICS(plan: Array<{ day: number; theme: string; hook?: string; caption?: string; cta?: string }>, opts?: { brand?: string; startDate?: Date }) {
  const start = opts?.startDate ?? new Date();
  start.setHours(9, 0, 0, 0);
  const lines: string[] = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//ContentNaija AI//Content Calendar//EN",
    "CALSCALE:GREGORIAN",
  ];
  for (const d of plan) {
    const dt = new Date(start);
    dt.setDate(start.getDate() + (d.day - 1));
    const dtEnd = new Date(dt);
    dtEnd.setMinutes(dt.getMinutes() + 30);
    const summary = `${opts?.brand ? opts.brand + " — " : ""}Day ${d.day}: ${d.theme}`;
    const desc = [d.hook, d.caption, d.cta ? `CTA: ${d.cta}` : ""].filter(Boolean).join("\\n\\n");
    lines.push(
      "BEGIN:VEVENT",
      `UID:${crypto.randomUUID()}@contentnaija.ai`,
      `DTSTAMP:${fmtDate(new Date())}`,
      `DTSTART:${fmtDate(dt)}`,
      `DTEND:${fmtDate(dtEnd)}`,
      `SUMMARY:${icsEscape(summary)}`,
      `DESCRIPTION:${icsEscape(desc)}`,
      "END:VEVENT",
    );
  }
  lines.push("END:VCALENDAR");
  downloadBlob(lines.join("\r\n"), "content-calendar.ics", "text/calendar");
}
