/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedGenerateIndexRouteImport } from './routes/_authenticated/generate.index'
import { Route as AuthenticatedGenerateWhatsappRouteImport } from './routes/_authenticated/generate.whatsapp'
import { Route as AuthenticatedGenerateInstagramRouteImport } from './routes/_authenticated/generate.instagram'
import { Route as AuthenticatedGenerateImageRouteImport } from './routes/_authenticated/generate.image'
import { Route as AuthenticatedGenerateFlyerRouteImport } from './routes/_authenticated/generate.flyer'
import { Route as AuthenticatedGenerateCalendarRouteImport } from './routes/_authenticated/generate.calendar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGenerateIndexRoute =
  AuthenticatedGenerateIndexRouteImport.update({
    id: '/generate/',
    path: '/generate/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateWhatsappRoute =
  AuthenticatedGenerateWhatsappRouteImport.update({
    id: '/generate/whatsapp',
    path: '/generate/whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateInstagramRoute =
  AuthenticatedGenerateInstagramRouteImport.update({
    id: '/generate/instagram',
    path: '/generate/instagram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateImageRoute =
  AuthenticatedGenerateImageRouteImport.update({
    id: '/generate/image',
    path: '/generate/image',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateFlyerRoute =
  AuthenticatedGenerateFlyerRouteImport.update({
    id: '/generate/flyer',
    path: '/generate/flyer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateCalendarRoute =
  AuthenticatedGenerateCalendarRouteImport.update({
    id: '/generate/calendar',
    path: '/generate/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/s/$token': typeof STokenRoute
  '/generate/calendar': typeof AuthenticatedGenerateCalendarRoute
  '/generate/flyer': typeof AuthenticatedGenerateFlyerRoute
  '/generate/image': typeof AuthenticatedGenerateImageRoute
  '/generate/instagram': typeof AuthenticatedGenerateInstagramRoute
  '/generate/whatsapp': typeof AuthenticatedGenerateWhatsappRoute
  '/generate/': typeof AuthenticatedGenerateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/s/$token': typeof STokenRoute
  '/generate/calendar': typeof AuthenticatedGenerateCalendarRoute
  '/generate/flyer': typeof AuthenticatedGenerateFlyerRoute
  '/generate/image': typeof AuthenticatedGenerateImageRoute
  '/generate/instagram': typeof AuthenticatedGenerateInstagramRoute
  '/generate/whatsapp': typeof AuthenticatedGenerateWhatsappRoute
  '/generate': typeof AuthenticatedGenerateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/s/$token': typeof STokenRoute
  '/_authenticated/generate/calendar': typeof AuthenticatedGenerateCalendarRoute
  '/_authenticated/generate/flyer': typeof AuthenticatedGenerateFlyerRoute
  '/_authenticated/generate/image': typeof AuthenticatedGenerateImageRoute
  '/_authenticated/generate/instagram': typeof AuthenticatedGenerateInstagramRoute
  '/_authenticated/generate/whatsapp': typeof AuthenticatedGenerateWhatsappRoute
  '/_authenticated/generate/': typeof AuthenticatedGenerateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/analytics'
    | '/brands'
    | '/dashboard'
    | '/history'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/team'
    | '/s/$token'
    | '/generate/calendar'
    | '/generate/flyer'
    | '/generate/image'
    | '/generate/instagram'
    | '/generate/whatsapp'
    | '/generate/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/admin'
    | '/analytics'
    | '/brands'
    | '/dashboard'
    | '/history'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/team'
    | '/s/$token'
    | '/generate/calendar'
    | '/generate/flyer'
    | '/generate/image'
    | '/generate/instagram'
    | '/generate/whatsapp'
    | '/generate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/brands'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/onboarding'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/s/$token'
    | '/_authenticated/generate/calendar'
    | '/_authenticated/generate/flyer'
    | '/_authenticated/generate/image'
    | '/_authenticated/generate/instagram'
    | '/_authenticated/generate/whatsapp'
    | '/_authenticated/generate/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/': {
      id: '/_authenticated/generate/'
      path: '/generate'
      fullPath: '/generate/'
      preLoaderRoute: typeof AuthenticatedGenerateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/whatsapp': {
      id: '/_authenticated/generate/whatsapp'
      path: '/generate/whatsapp'
      fullPath: '/generate/whatsapp'
      preLoaderRoute: typeof AuthenticatedGenerateWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/instagram': {
      id: '/_authenticated/generate/instagram'
      path: '/generate/instagram'
      fullPath: '/generate/instagram'
      preLoaderRoute: typeof AuthenticatedGenerateInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/image': {
      id: '/_authenticated/generate/image'
      path: '/generate/image'
      fullPath: '/generate/image'
      preLoaderRoute: typeof AuthenticatedGenerateImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/flyer': {
      id: '/_authenticated/generate/flyer'
      path: '/generate/flyer'
      fullPath: '/generate/flyer'
      preLoaderRoute: typeof AuthenticatedGenerateFlyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/calendar': {
      id: '/_authenticated/generate/calendar'
      path: '/generate/calendar'
      fullPath: '/generate/calendar'
      preLoaderRoute: typeof AuthenticatedGenerateCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedGenerateCalendarRoute: typeof AuthenticatedGenerateCalendarRoute
  AuthenticatedGenerateFlyerRoute: typeof AuthenticatedGenerateFlyerRoute
  AuthenticatedGenerateImageRoute: typeof AuthenticatedGenerateImageRoute
  AuthenticatedGenerateInstagramRoute: typeof AuthenticatedGenerateInstagramRoute
  AuthenticatedGenerateWhatsappRoute: typeof AuthenticatedGenerateWhatsappRoute
  AuthenticatedGenerateIndexRoute: typeof AuthenticatedGenerateIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedGenerateCalendarRoute: AuthenticatedGenerateCalendarRoute,
  AuthenticatedGenerateFlyerRoute: AuthenticatedGenerateFlyerRoute,
  AuthenticatedGenerateImageRoute: AuthenticatedGenerateImageRoute,
  AuthenticatedGenerateInstagramRoute: AuthenticatedGenerateInstagramRoute,
  AuthenticatedGenerateWhatsappRoute: AuthenticatedGenerateWhatsappRoute,
  AuthenticatedGenerateIndexRoute: AuthenticatedGenerateIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
