/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesSlugRouteImport } from './routes/templates.$slug'
import { Route as STokenRouteImport } from './routes/s.$token'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ForIndustryRouteImport } from './routes/for.$industry'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandsRouteImport } from './routes/_authenticated/brands'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedWhatsappIndexRouteImport } from './routes/_authenticated/whatsapp.index'
import { Route as AuthenticatedGenerateIndexRouteImport } from './routes/_authenticated/generate.index'
import { Route as AuthenticatedWhatsappStatusRouteImport } from './routes/_authenticated/whatsapp.status'
import { Route as AuthenticatedWhatsappPromoRouteImport } from './routes/_authenticated/whatsapp.promo'
import { Route as AuthenticatedWhatsappFollowupRouteImport } from './routes/_authenticated/whatsapp.followup'
import { Route as AuthenticatedWhatsappBroadcastRouteImport } from './routes/_authenticated/whatsapp.broadcast'
import { Route as AuthenticatedGenerateWhatsappRouteImport } from './routes/_authenticated/generate.whatsapp'
import { Route as AuthenticatedGenerateInstagramRouteImport } from './routes/_authenticated/generate.instagram'
import { Route as AuthenticatedGenerateImageRouteImport } from './routes/_authenticated/generate.image'
import { Route as AuthenticatedGenerateFlyerRouteImport } from './routes/_authenticated/generate.flyer'
import { Route as AuthenticatedGenerateCalendarRouteImport } from './routes/_authenticated/generate.calendar'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesSlugRoute = TemplatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TemplatesRoute,
} as any)
const STokenRoute = STokenRouteImport.update({
  id: '/s/$token',
  path: '/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ForIndustryRoute = ForIndustryRouteImport.update({
  id: '/for/$industry',
  path: '/for/$industry',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandsRoute = AuthenticatedBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappIndexRoute =
  AuthenticatedWhatsappIndexRouteImport.update({
    id: '/whatsapp/',
    path: '/whatsapp/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateIndexRoute =
  AuthenticatedGenerateIndexRouteImport.update({
    id: '/generate/',
    path: '/generate/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappStatusRoute =
  AuthenticatedWhatsappStatusRouteImport.update({
    id: '/whatsapp/status',
    path: '/whatsapp/status',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappPromoRoute =
  AuthenticatedWhatsappPromoRouteImport.update({
    id: '/whatsapp/promo',
    path: '/whatsapp/promo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappFollowupRoute =
  AuthenticatedWhatsappFollowupRouteImport.update({
    id: '/whatsapp/followup',
    path: '/whatsapp/followup',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWhatsappBroadcastRoute =
  AuthenticatedWhatsappBroadcastRouteImport.update({
    id: '/whatsapp/broadcast',
    path: '/whatsapp/broadcast',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateWhatsappRoute =
  AuthenticatedGenerateWhatsappRouteImport.update({
    id: '/generate/whatsapp',
    path: '/generate/whatsapp',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateInstagramRoute =
  AuthenticatedGenerateInstagramRouteImport.update({
    id: '/generate/instagram',
    path: '/generate/instagram',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateImageRoute =
  AuthenticatedGenerateImageRouteImport.update({
    id: '/generate/image',
    path: '/generate/image',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateFlyerRoute =
  AuthenticatedGenerateFlyerRouteImport.update({
    id: '/generate/flyer',
    path: '/generate/flyer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerateCalendarRoute =
  AuthenticatedGenerateCalendarRouteImport.update({
    id: '/generate/calendar',
    path: '/generate/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/for/$industry': typeof ForIndustryRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$token': typeof STokenRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/generate/calendar': typeof AuthenticatedGenerateCalendarRoute
  '/generate/flyer': typeof AuthenticatedGenerateFlyerRoute
  '/generate/image': typeof AuthenticatedGenerateImageRoute
  '/generate/instagram': typeof AuthenticatedGenerateInstagramRoute
  '/generate/whatsapp': typeof AuthenticatedGenerateWhatsappRoute
  '/whatsapp/broadcast': typeof AuthenticatedWhatsappBroadcastRoute
  '/whatsapp/followup': typeof AuthenticatedWhatsappFollowupRoute
  '/whatsapp/promo': typeof AuthenticatedWhatsappPromoRoute
  '/whatsapp/status': typeof AuthenticatedWhatsappStatusRoute
  '/generate/': typeof AuthenticatedGenerateIndexRoute
  '/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/brands': typeof AuthenticatedBrandsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/for/$industry': typeof ForIndustryRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$token': typeof STokenRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/generate/calendar': typeof AuthenticatedGenerateCalendarRoute
  '/generate/flyer': typeof AuthenticatedGenerateFlyerRoute
  '/generate/image': typeof AuthenticatedGenerateImageRoute
  '/generate/instagram': typeof AuthenticatedGenerateInstagramRoute
  '/generate/whatsapp': typeof AuthenticatedGenerateWhatsappRoute
  '/whatsapp/broadcast': typeof AuthenticatedWhatsappBroadcastRoute
  '/whatsapp/followup': typeof AuthenticatedWhatsappFollowupRoute
  '/whatsapp/promo': typeof AuthenticatedWhatsappPromoRoute
  '/whatsapp/status': typeof AuthenticatedWhatsappStatusRoute
  '/generate': typeof AuthenticatedGenerateIndexRoute
  '/whatsapp': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/brands': typeof AuthenticatedBrandsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/for/$industry': typeof ForIndustryRoute
  '/invite/$token': typeof InviteTokenRoute
  '/s/$token': typeof STokenRoute
  '/templates/$slug': typeof TemplatesSlugRoute
  '/_authenticated/generate/calendar': typeof AuthenticatedGenerateCalendarRoute
  '/_authenticated/generate/flyer': typeof AuthenticatedGenerateFlyerRoute
  '/_authenticated/generate/image': typeof AuthenticatedGenerateImageRoute
  '/_authenticated/generate/instagram': typeof AuthenticatedGenerateInstagramRoute
  '/_authenticated/generate/whatsapp': typeof AuthenticatedGenerateWhatsappRoute
  '/_authenticated/whatsapp/broadcast': typeof AuthenticatedWhatsappBroadcastRoute
  '/_authenticated/whatsapp/followup': typeof AuthenticatedWhatsappFollowupRoute
  '/_authenticated/whatsapp/promo': typeof AuthenticatedWhatsappPromoRoute
  '/_authenticated/whatsapp/status': typeof AuthenticatedWhatsappStatusRoute
  '/_authenticated/generate/': typeof AuthenticatedGenerateIndexRoute
  '/_authenticated/whatsapp/': typeof AuthenticatedWhatsappIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/templates'
    | '/admin'
    | '/analytics'
    | '/brands'
    | '/dashboard'
    | '/history'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/team'
    | '/blog/$slug'
    | '/for/$industry'
    | '/invite/$token'
    | '/s/$token'
    | '/templates/$slug'
    | '/generate/calendar'
    | '/generate/flyer'
    | '/generate/image'
    | '/generate/instagram'
    | '/generate/whatsapp'
    | '/whatsapp/broadcast'
    | '/whatsapp/followup'
    | '/whatsapp/promo'
    | '/whatsapp/status'
    | '/generate/'
    | '/whatsapp/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/templates'
    | '/admin'
    | '/analytics'
    | '/brands'
    | '/dashboard'
    | '/history'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/team'
    | '/blog/$slug'
    | '/for/$industry'
    | '/invite/$token'
    | '/s/$token'
    | '/templates/$slug'
    | '/generate/calendar'
    | '/generate/flyer'
    | '/generate/image'
    | '/generate/instagram'
    | '/generate/whatsapp'
    | '/whatsapp/broadcast'
    | '/whatsapp/followup'
    | '/whatsapp/promo'
    | '/whatsapp/status'
    | '/generate'
    | '/whatsapp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/blog'
    | '/contact'
    | '/forgot-password'
    | '/pricing'
    | '/reset-password'
    | '/sitemap.xml'
    | '/templates'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/brands'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/onboarding'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/team'
    | '/blog/$slug'
    | '/for/$industry'
    | '/invite/$token'
    | '/s/$token'
    | '/templates/$slug'
    | '/_authenticated/generate/calendar'
    | '/_authenticated/generate/flyer'
    | '/_authenticated/generate/image'
    | '/_authenticated/generate/instagram'
    | '/_authenticated/generate/whatsapp'
    | '/_authenticated/whatsapp/broadcast'
    | '/_authenticated/whatsapp/followup'
    | '/_authenticated/whatsapp/promo'
    | '/_authenticated/whatsapp/status'
    | '/_authenticated/generate/'
    | '/_authenticated/whatsapp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  ForIndustryRoute: typeof ForIndustryRoute
  InviteTokenRoute: typeof InviteTokenRoute
  STokenRoute: typeof STokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/$slug': {
      id: '/templates/$slug'
      path: '/$slug'
      fullPath: '/templates/$slug'
      preLoaderRoute: typeof TemplatesSlugRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/s/$token': {
      id: '/s/$token'
      path: '/s/$token'
      fullPath: '/s/$token'
      preLoaderRoute: typeof STokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for/$industry': {
      id: '/for/$industry'
      path: '/for/$industry'
      fullPath: '/for/$industry'
      preLoaderRoute: typeof ForIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands': {
      id: '/_authenticated/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/': {
      id: '/_authenticated/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof AuthenticatedWhatsappIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/': {
      id: '/_authenticated/generate/'
      path: '/generate'
      fullPath: '/generate/'
      preLoaderRoute: typeof AuthenticatedGenerateIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/status': {
      id: '/_authenticated/whatsapp/status'
      path: '/whatsapp/status'
      fullPath: '/whatsapp/status'
      preLoaderRoute: typeof AuthenticatedWhatsappStatusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/promo': {
      id: '/_authenticated/whatsapp/promo'
      path: '/whatsapp/promo'
      fullPath: '/whatsapp/promo'
      preLoaderRoute: typeof AuthenticatedWhatsappPromoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/followup': {
      id: '/_authenticated/whatsapp/followup'
      path: '/whatsapp/followup'
      fullPath: '/whatsapp/followup'
      preLoaderRoute: typeof AuthenticatedWhatsappFollowupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp/broadcast': {
      id: '/_authenticated/whatsapp/broadcast'
      path: '/whatsapp/broadcast'
      fullPath: '/whatsapp/broadcast'
      preLoaderRoute: typeof AuthenticatedWhatsappBroadcastRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/whatsapp': {
      id: '/_authenticated/generate/whatsapp'
      path: '/generate/whatsapp'
      fullPath: '/generate/whatsapp'
      preLoaderRoute: typeof AuthenticatedGenerateWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/instagram': {
      id: '/_authenticated/generate/instagram'
      path: '/generate/instagram'
      fullPath: '/generate/instagram'
      preLoaderRoute: typeof AuthenticatedGenerateInstagramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/image': {
      id: '/_authenticated/generate/image'
      path: '/generate/image'
      fullPath: '/generate/image'
      preLoaderRoute: typeof AuthenticatedGenerateImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/flyer': {
      id: '/_authenticated/generate/flyer'
      path: '/generate/flyer'
      fullPath: '/generate/flyer'
      preLoaderRoute: typeof AuthenticatedGenerateFlyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generate/calendar': {
      id: '/_authenticated/generate/calendar'
      path: '/generate/calendar'
      fullPath: '/generate/calendar'
      preLoaderRoute: typeof AuthenticatedGenerateCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBrandsRoute: typeof AuthenticatedBrandsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedGenerateCalendarRoute: typeof AuthenticatedGenerateCalendarRoute
  AuthenticatedGenerateFlyerRoute: typeof AuthenticatedGenerateFlyerRoute
  AuthenticatedGenerateImageRoute: typeof AuthenticatedGenerateImageRoute
  AuthenticatedGenerateInstagramRoute: typeof AuthenticatedGenerateInstagramRoute
  AuthenticatedGenerateWhatsappRoute: typeof AuthenticatedGenerateWhatsappRoute
  AuthenticatedWhatsappBroadcastRoute: typeof AuthenticatedWhatsappBroadcastRoute
  AuthenticatedWhatsappFollowupRoute: typeof AuthenticatedWhatsappFollowupRoute
  AuthenticatedWhatsappPromoRoute: typeof AuthenticatedWhatsappPromoRoute
  AuthenticatedWhatsappStatusRoute: typeof AuthenticatedWhatsappStatusRoute
  AuthenticatedGenerateIndexRoute: typeof AuthenticatedGenerateIndexRoute
  AuthenticatedWhatsappIndexRoute: typeof AuthenticatedWhatsappIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBrandsRoute: AuthenticatedBrandsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedGenerateCalendarRoute: AuthenticatedGenerateCalendarRoute,
  AuthenticatedGenerateFlyerRoute: AuthenticatedGenerateFlyerRoute,
  AuthenticatedGenerateImageRoute: AuthenticatedGenerateImageRoute,
  AuthenticatedGenerateInstagramRoute: AuthenticatedGenerateInstagramRoute,
  AuthenticatedGenerateWhatsappRoute: AuthenticatedGenerateWhatsappRoute,
  AuthenticatedWhatsappBroadcastRoute: AuthenticatedWhatsappBroadcastRoute,
  AuthenticatedWhatsappFollowupRoute: AuthenticatedWhatsappFollowupRoute,
  AuthenticatedWhatsappPromoRoute: AuthenticatedWhatsappPromoRoute,
  AuthenticatedWhatsappStatusRoute: AuthenticatedWhatsappStatusRoute,
  AuthenticatedGenerateIndexRoute: AuthenticatedGenerateIndexRoute,
  AuthenticatedWhatsappIndexRoute: AuthenticatedWhatsappIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface TemplatesRouteChildren {
  TemplatesSlugRoute: typeof TemplatesSlugRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesSlugRoute: TemplatesSlugRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  ForIndustryRoute: ForIndustryRoute,
  InviteTokenRoute: InviteTokenRoute,
  STokenRoute: STokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
